/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Validaciones.Caracteres;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/**
 *
 * @author Kevin Benitez
 */
public class VtnModifica extends javax.swing.JDialog
{

    public static JDialog vtn;
    public static String[] arr = new String[8];

    String nombre = "";
    String placas = "";
    String color = "";
    String marca = "";
    String tamaño = "";
    String registro = "";
    String credencialAnver = "";
    String credencialRever = "";
    String tarjCirculacion = "";
    
    BufferedImage img1;
    BufferedImage img2;
    BufferedImage img3;
    //Lectura de imagenes desde la base de datos

    /**
     * Creates new form VtnRegistro
     *
     * @param registro
     * @param codigo_b
     * @param nombre
     * @param anv
     * @param rev
     * @param tc
     * @param placas
     * @param marca
     * @param color
     * @param tamaño
     */
    public VtnModifica(String registro,String codigo_b, String nombre, byte[] anv, byte[] rev, byte[] tc, String placas, String color, String marca, String tamaño)
    {
        initComponents();
        setLocationRelativeTo(null);
        vtn = this;
        jBSalir.setBackground(new Color(0, 0, 0, 0));
        this.jLNRegistro.setText(registro);
        this.jTNombre.setText(nombre);
        this.jTPlacas.setText(placas);
        this.jTMarca.setText(marca);
        this.jTColor.setText(color);
        this.jCTamaño.setSelectedItem(tamaño);
        this.jTCode.setText(codigo_b);
        try
        {
            img1 = ImageIO.read(new ByteArrayInputStream(anv));
            img2 = ImageIO.read(new ByteArrayInputStream(rev));
            img3 = ImageIO.read(new ByteArrayInputStream(tc));
            Image anvv = img1;
            Image revv = img2;
            Image tcc = img3;
            ImageIcon icon1 = new ImageIcon(img1.getScaledInstance(lblCredencialAnver.getWidth(), lblCredencialAnver.getHeight(), Image.SCALE_DEFAULT));
            ImageIcon icon2 = new ImageIcon(img2.getScaledInstance(lblCredencialRever.getWidth(), lblCredencialRever.getHeight(), Image.SCALE_DEFAULT));
            ImageIcon icon3 = new ImageIcon(img3.getScaledInstance(lblTarjCirculacion.getWidth(), lblTarjCirculacion.getHeight(), Image.SCALE_DEFAULT));
            lblCredencialAnver.setText("");
            lblCredencialAnver.setIcon(icon1);
            lblCredencialRever.setText("");
            lblCredencialRever.setIcon(icon2);
            lblTarjCirculacion.setText("");
            lblTarjCirculacion.setIcon(icon3);
            jPanel3.updateUI();
        } catch (IOException e)
        {
            System.out.println("ERROR DE IMAGEN"+e);
        }
    }

    private VtnModifica()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLNRegistro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBanv = new javax.swing.JButton();
        jBrev = new javax.swing.JButton();
        jBtc = new javax.swing.JButton();
        lblCredencialAnver = new javax.swing.JLabel();
        lblCredencialRever = new javax.swing.JLabel();
        lblTarjCirculacion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCTamaño = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTCode = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTNombre = new javax.swing.JTextField();
        jTPlacas = new javax.swing.JTextField();
        jTMarca = new javax.swing.JTextField();
        jTColor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Modificar registro");

        jBSalir.setBackground(new java.awt.Color(0, 0, 0));
        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cross-symbol_icon-icons.com_74149.png"))); // NOI18N
        jBSalir.setToolTipText("");
        jBSalir.setBorder(null);
        jBSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/about_3697.png"))); // NOI18N
        jLabel14.setToolTipText("Ventana para modificar un registro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Datos del incorporado");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("No. Registro");

        jLNRegistro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLNRegistro.setText("----");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Documentacion:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 3));

        jBanv.setBackground(new java.awt.Color(0, 80, 0));
        jBanv.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBanv.setForeground(new java.awt.Color(255, 255, 255));
        jBanv.setText("Modificar imagen");
        jBanv.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jBanv.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBanvActionPerformed(evt);
            }
        });

        jBrev.setBackground(new java.awt.Color(0, 80, 0));
        jBrev.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBrev.setForeground(new java.awt.Color(255, 255, 255));
        jBrev.setText("Modificar imagen");
        jBrev.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jBrev.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBrevActionPerformed(evt);
            }
        });

        jBtc.setBackground(new java.awt.Color(0, 80, 0));
        jBtc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jBtc.setForeground(new java.awt.Color(255, 255, 255));
        jBtc.setText("Modificar imagen");
        jBtc.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jBtc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtcActionPerformed(evt);
            }
        });

        lblCredencialAnver.setText(" Credencial Institucional Anverso");
        lblCredencialAnver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 3));

        lblCredencialRever.setText(" Credencial Institucional Reverso");
        lblCredencialRever.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 3));

        lblTarjCirculacion.setText("                    Tarjeta de circulacion");
        lblTarjCirculacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblCredencialAnver))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBanv, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblCredencialRever, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTarjCirculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jBrev, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBanv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBrev, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredencialAnver, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredencialRever, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTarjCirculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("Datos del vehiculo");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setText("Placas:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setText("Marca:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setText("Color:");

        jCTamaño.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tamaño", "Pequeño", "Mediano", "Grande" }));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setText("Codigo de barras");

        jTCode.setEditable(false);
        jTCode.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTCode.setForeground(new java.awt.Color(0, 80, 0));
        jTCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTCode.setFocusable(false);
        jTCode.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTCodeFocusLost(evt);
            }
        });
        jTCode.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTCodeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jTCode, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jTCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButton7.setBackground(new java.awt.Color(0, 80, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Guardar cambios");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jButton7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(139, 116, 1));
        jButton8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Cancelar");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jButton8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton8ActionPerformed(evt);
            }
        });

        jTNombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTNombre.setForeground(new java.awt.Color(0, 80, 0));
        jTNombre.setText("Ingrese nombre completo aqui");
        jTNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTNombre.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTNombreFocusLost(evt);
            }
        });
        jTNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTNombreKeyTyped(evt);
            }
        });

        jTPlacas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTPlacas.setForeground(new java.awt.Color(0, 80, 0));
        jTPlacas.setText("Ingrese el numero de placas");
        jTPlacas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTPlacas.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTPlacasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTPlacasFocusLost(evt);
            }
        });
        jTPlacas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTPlacasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTPlacasKeyTyped(evt);
            }
        });

        jTMarca.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTMarca.setForeground(new java.awt.Color(0, 80, 0));
        jTMarca.setText("Ingrese la marca");
        jTMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTMarca.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTMarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTMarcaFocusLost(evt);
            }
        });
        jTMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTMarcaActionPerformed(evt);
            }
        });
        jTMarca.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTMarcaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTMarcaKeyTyped(evt);
            }
        });

        jTColor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTColor.setForeground(new java.awt.Color(0, 80, 0));
        jTColor.setText("Ingrese el color");
        jTColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTColor.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTColorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTColorFocusLost(evt);
            }
        });
        jTColor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTColorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTColorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLNRegistro)
                                        .addGap(11, 11, 11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTColor, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLNRegistro)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jCTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBSalirActionPerformed
    {//GEN-HEADEREND:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBrevActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBrevActionPerformed
    {//GEN-HEADEREND:event_jBrevActionPerformed
        JFileChooser credRever = new JFileChooser();
        int opc = credRever.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION)
        {
            String ruta = credRever.getSelectedFile().getPath();
            rsscalelabel.RSScaleLabel.setScaleLabel(lblCredencialRever, ruta);
            lblCredencialRever.setText(credRever.getSelectedFile().getName());
            credencialRever = ruta;
            arr[2] = credencialRever;
        } else
        {
            System.out.println("No se selecciono ningun archivo.");
        }
    }//GEN-LAST:event_jBrevActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        if (!jTNombre.getText().isEmpty()
                && !jTNombre.getText().isEmpty()
                && !jTPlacas.getText().isEmpty()
                && !jTColor.getText().isEmpty()
                && !jTMarca.getText().isEmpty()
                && (jCTamaño.getSelectedItem().equals("Pequeño")
                || jCTamaño.getSelectedItem().equals("Mediano")
                || jCTamaño.getSelectedItem().equals("Grande")))
        {
            arr[0] = jTNombre.getText();
            arr[4] = jTPlacas.getText();
            arr[5] = jTColor.getText();
            arr[6] = jTMarca.getText();
            arr[7] = jCTamaño.getSelectedItem().toString();

            ConfirmacionModificarV confirma = new ConfirmacionModificarV(this, true, 1);
            ConfirmacionModificarV.arr = arr;

            confirma.setModal(true);
            confirma.setVisible(true);
        } else
        {
            if (jTNombre.getText().isEmpty()
                    || !jTNombre.getText().isEmpty()
                    || !jTPlacas.getText().isEmpty()
                    || !jTMarca.getText().isEmpty()
                    || !jTColor.getText().isEmpty()
                    && (jCTamaño.getSelectedItem().equals("Pequeño")
                    || jCTamaño.getSelectedItem().equals("Mediano")
                    || jCTamaño.getSelectedItem().equals("Grande")))
            {
                ErrorCampos codigo = new ErrorCampos(null, true);
                codigo.setModal(true);
                codigo.setVisible(true);
            }
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton8ActionPerformed
    {//GEN-HEADEREND:event_jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTCodeKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTCodeKeyTyped
    {//GEN-HEADEREND:event_jTCodeKeyTyped
        if (jTCode.getText().length() == 12)
        {
            evt.consume();
        } else
        {
            Character c = evt.getKeyChar();
            if (Character.isDigit(c))
            {
                evt.setKeyChar(c);
            } else
            {
                evt.setKeyChar('\b');
            }
        }
    }//GEN-LAST:event_jTCodeKeyTyped

    private void jBanvActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBanvActionPerformed
    {//GEN-HEADEREND:event_jBanvActionPerformed
        JFileChooser credAnver = new JFileChooser();
        int opc = credAnver.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION)
        {
            String ruta = credAnver.getSelectedFile().getPath();
            rsscalelabel.RSScaleLabel.setScaleLabel(lblCredencialAnver, ruta);
            lblCredencialAnver.setText(credAnver.getSelectedFile().getName());
            credencialAnver = ruta;
            arr[1] = credencialAnver;
        } else
        {
            System.out.println("No se selecciono ningun archivo.");
        }
    }//GEN-LAST:event_jBanvActionPerformed

    private void jBtcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtcActionPerformed
    {//GEN-HEADEREND:event_jBtcActionPerformed
        JFileChooser tarjCirc = new JFileChooser();
        int opc = tarjCirc.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION)
        {
            String ruta = tarjCirc.getSelectedFile().getPath();
            rsscalelabel.RSScaleLabel.setScaleLabel(lblTarjCirculacion, ruta);
            lblTarjCirculacion.setText(tarjCirc.getSelectedFile().getName());
            tarjCirculacion = ruta;
            arr[3] = tarjCirculacion;
        } else
        {
            System.out.println("No se selecciono ningun archivo.");
        }
    }//GEN-LAST:event_jBtcActionPerformed

    private void jTCodeFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTCodeFocusGained
    {//GEN-HEADEREND:event_jTCodeFocusGained
        jTCode.setText(null);
    }//GEN-LAST:event_jTCodeFocusGained

    private void jTCodeFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTCodeFocusLost
    {//GEN-HEADEREND:event_jTCodeFocusLost
        jTCode.setText("Aquí se mostrará el código de barras");
    }//GEN-LAST:event_jTCodeFocusLost

    private void jTNombreFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTNombreFocusGained
    {//GEN-HEADEREND:event_jTNombreFocusGained
        if (!Caracteres.comparacion(jTNombre.getText(), "Ingrese nombre completo aqui"))
        {
            jTNombre.setText(null);
        }
    }//GEN-LAST:event_jTNombreFocusGained

    private void jTNombreFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTNombreFocusLost
    {//GEN-HEADEREND:event_jTNombreFocusLost
        nombre = jTNombre.getText();
        if (!Caracteres.comparacion(nombre, "Ingrese nombre completo aqui"))
        {
            jTNombre.setText("Ingrese nombre completo aqui");
        }
    }//GEN-LAST:event_jTNombreFocusLost

    private void jTNombreKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTNombreKeyReleased
    {//GEN-HEADEREND:event_jTNombreKeyReleased
        nombre = jTNombre.getText();
    }//GEN-LAST:event_jTNombreKeyReleased

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTNombreKeyTyped
    {//GEN-HEADEREND:event_jTNombreKeyTyped
        if (jTNombre.getText().length() == 30)
        {
            evt.consume();
        } else
        {
            Caracteres.va(evt);
        }
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTPlacasFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTPlacasFocusGained
    {//GEN-HEADEREND:event_jTPlacasFocusGained
        if (!Caracteres.comparacion(placas, "Ingrese el numero de placas"))
        {
            jTPlacas.setText(null);
        }
    }//GEN-LAST:event_jTPlacasFocusGained

    private void jTPlacasFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTPlacasFocusLost
    {//GEN-HEADEREND:event_jTPlacasFocusLost
        if (!Caracteres.comparacion(placas, "Ingrese el numero de placas"))
        {
            jTPlacas.setText("Ingrese el numero de placas");
        }
    }//GEN-LAST:event_jTPlacasFocusLost

    private void jTPlacasKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTPlacasKeyReleased
    {//GEN-HEADEREND:event_jTPlacasKeyReleased
        placas = jTPlacas.getText();
    }//GEN-LAST:event_jTPlacasKeyReleased

    private void jTPlacasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTPlacasKeyTyped
    {//GEN-HEADEREND:event_jTPlacasKeyTyped
        if (jTPlacas.getText().length() == 9)
        {
            evt.consume();
        } else
        {
            Character c = evt.getKeyChar();
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTPlacasKeyTyped

    private void jTMarcaFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTMarcaFocusGained
    {//GEN-HEADEREND:event_jTMarcaFocusGained
        if (!Caracteres.comparacion(marca, "Ingrese la marca"))
        {
            jTMarca.setText(null);
        }
    }//GEN-LAST:event_jTMarcaFocusGained

    private void jTMarcaFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTMarcaFocusLost
    {//GEN-HEADEREND:event_jTMarcaFocusLost
        if (!Caracteres.comparacion(marca, "Ingrese la marca"))
        {
            jTMarca.setText("Ingrese la marca");
        }
    }//GEN-LAST:event_jTMarcaFocusLost

    private void jTMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTMarcaActionPerformed
    {//GEN-HEADEREND:event_jTMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMarcaActionPerformed

    private void jTMarcaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTMarcaKeyReleased
    {//GEN-HEADEREND:event_jTMarcaKeyReleased
        marca = jTMarca.getText();
    }//GEN-LAST:event_jTMarcaKeyReleased

    private void jTMarcaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTMarcaKeyTyped
    {//GEN-HEADEREND:event_jTMarcaKeyTyped
        if (jTMarca.getText().length() == 15)
        {
            evt.consume();
        } else
        {
            Caracteres.va(evt);
        }
    }//GEN-LAST:event_jTMarcaKeyTyped

    private void jTColorFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTColorFocusGained
    {//GEN-HEADEREND:event_jTColorFocusGained
        if (!Caracteres.comparacion(color, "Ingrese el color"))
        {
            jTColor.setText(null);
        }
    }//GEN-LAST:event_jTColorFocusGained

    private void jTColorFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTColorFocusLost
    {//GEN-HEADEREND:event_jTColorFocusLost
        if (!Caracteres.comparacion(color, "Ingrese el color"))
        {
            jTColor.setText("Ingrese el color");
        }
    }//GEN-LAST:event_jTColorFocusLost

    private void jTColorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTColorKeyReleased
    {//GEN-HEADEREND:event_jTColorKeyReleased
        color = jTColor.getText();
    }//GEN-LAST:event_jTColorKeyReleased

    private void jTColorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTColorKeyTyped
    {//GEN-HEADEREND:event_jTColorKeyTyped
        if (jTColor.getText().length() == 15)
        {
            evt.consume();
        } else
        {
            Caracteres.va(evt);
        }
    }//GEN-LAST:event_jTColorKeyTyped

    public static void cierra()
    {
        vtn.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnModifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnModifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnModifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnModifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnModifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBanv;
    private javax.swing.JButton jBrev;
    private javax.swing.JButton jBtc;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jCTamaño;
    private javax.swing.JLabel jLNRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTCode;
    private javax.swing.JTextField jTColor;
    private javax.swing.JTextField jTMarca;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPlacas;
    private javax.swing.JLabel lblCredencialAnver;
    private javax.swing.JLabel lblCredencialRever;
    private javax.swing.JLabel lblTarjCirculacion;
    // End of variables declaration//GEN-END:variables
}
