package Ventanas;

import Validaciones.Caracteres;
import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import jbarcodebean.JBarcodeBean;
import metodosBaseDatos.MetodosCRUD;
import net.sourceforge.jbarcodebean.model.Interleaved25;

public class VtnRegistroVhIncorp extends javax.swing.JDialog
{

    //Variables globales
    boolean imagen1 = false;
    boolean imagen2 = false;
    boolean imagen3 = false;
    String nombre = "";
    String credencialAnver = "";
    String credencialRever = "";
    String tarjCirculacion = "";
    String placas = "";
    String color = "";
    String marca = "";
    String tamanio = "";

    JBarcodeBean barcode = new JBarcodeBean();
    public static BufferedImage imagen = null;

    /**
     * Creates new form VtnRegistro
     */
    public VtnRegistroVhIncorp()
    {
        initComponents();
        lblNoRegistro.setText(String.valueOf(MetodosCRUD.ultimoRegistro(1) + 1));
        jBSalir.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNoRegistro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCredencialAnver = new javax.swing.JButton();
        btnTarjCirculacion = new javax.swing.JButton();
        btnCredencialRever = new javax.swing.JButton();
        lblCredencialRever = new javax.swing.JLabel();
        lblTarjCirculacion = new javax.swing.JLabel();
        lblTxtCredencialAnver = new javax.swing.JLabel();
        lblTxtCredencialRever = new javax.swing.JLabel();
        lblTxtTarjCirculacion = new javax.swing.JLabel();
        lblCredencialAnver = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cBTamanio = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTNombre4 = new javax.swing.JTextField();
        lblCode = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jTNombre = new javax.swing.JTextField();
        jTPlacas = new javax.swing.JTextField();
        jTMarca = new javax.swing.JTextField();
        jTColor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Registro de nuevo vehiculo");

        jBSalir.setBackground(new java.awt.Color(0, 0, 0));
        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cross-symbol_icon-icons.com_74149.png"))); // NOI18N
        jBSalir.setToolTipText("");
        jBSalir.setBorder(null);
        jBSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/about_3697.png"))); // NOI18N
        jLabel14.setToolTipText("Ventana para dar de Alta a un Nuevo Registro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Datos del incorporado");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("No. Registro");

        lblNoRegistro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblNoRegistro.setText("-----");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Documentacion:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 3));

        btnCredencialAnver.setBackground(new java.awt.Color(0, 80, 0));
        btnCredencialAnver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnCredencialAnver.setForeground(new java.awt.Color(255, 255, 255));
        btnCredencialAnver.setText("Añadir imagen");
        btnCredencialAnver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCredencialAnver.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCredencialAnverActionPerformed(evt);
            }
        });

        btnTarjCirculacion.setBackground(new java.awt.Color(0, 80, 0));
        btnTarjCirculacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnTarjCirculacion.setForeground(new java.awt.Color(255, 255, 255));
        btnTarjCirculacion.setText("Añadir imagen");
        btnTarjCirculacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnTarjCirculacion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnTarjCirculacionActionPerformed(evt);
            }
        });

        btnCredencialRever.setBackground(new java.awt.Color(0, 80, 0));
        btnCredencialRever.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnCredencialRever.setForeground(new java.awt.Color(255, 255, 255));
        btnCredencialRever.setText("Añadir imagen");
        btnCredencialRever.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCredencialRever.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCredencialReverActionPerformed(evt);
            }
        });

        lblCredencialRever.setText(" Credencial Institucional Reverso");
        lblCredencialRever.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 3));

        lblTarjCirculacion.setText("                    Tarjeta de circulacion");
        lblTarjCirculacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 3));

        lblTxtCredencialAnver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        lblTxtCredencialAnver.setText("No ha seleccionado ninguna imagen");

        lblTxtCredencialRever.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        lblTxtCredencialRever.setText("No ha seleccionado ninguna imagen");

        lblTxtTarjCirculacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        lblTxtTarjCirculacion.setText("No ha seleccionado ninguna imagen");

        lblCredencialAnver.setText(" Credencial Institucional Anverso");
        lblCredencialAnver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTxtCredencialAnver)
                            .addComponent(btnCredencialAnver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCredencialAnver, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCredencialRever, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredencialRever, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTxtCredencialRever))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTarjCirculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTxtTarjCirculacion)
                    .addComponent(btnTarjCirculacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTarjCirculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCredencialAnver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCredencialRever, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTarjCirculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTxtTarjCirculacion))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCredencialRever, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCredencialAnver, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTxtCredencialAnver)
                            .addComponent(lblTxtCredencialRever))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("Datos del vehiculo");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setText("Placas:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setText("Marca:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setText("Color:");

        cBTamanio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cBTamanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tamaño", "Pequeño", "Mediano", "Grande" }));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel13.setText("Codigo de barras");

        jButton6.setBackground(new java.awt.Color(0, 80, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Visualizar");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });

        jTNombre4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTNombre4.setForeground(new java.awt.Color(0, 80, 0));
        jTNombre4.setText("Aquí se mostrará el código de barras");
        jTNombre4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTNombre4.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTNombre4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTNombre4FocusLost(evt);
            }
        });
        jTNombre4.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTNombre4KeyTyped(evt);
            }
        });

        lblCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(jTNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jButton7.setBackground(new java.awt.Color(0, 80, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Guardar nuevo registro");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jButton7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton7ActionPerformed(evt);
            }
        });

        jTNombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTNombre.setForeground(new java.awt.Color(0, 80, 0));
        jTNombre.setText("Ingrese nombre completo aqui");
        jTNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTNombre.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTNombreFocusLost(evt);
            }
        });
        jTNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTNombreKeyTyped(evt);
            }
        });

        jTPlacas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTPlacas.setForeground(new java.awt.Color(0, 80, 0));
        jTPlacas.setText("Ingrese el numero de placas");
        jTPlacas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTPlacas.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTPlacasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTPlacasFocusLost(evt);
            }
        });
        jTPlacas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTPlacasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTPlacasKeyTyped(evt);
            }
        });

        jTMarca.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTMarca.setForeground(new java.awt.Color(0, 80, 0));
        jTMarca.setText("Ingrese la marca");
        jTMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTMarca.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTMarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTMarcaFocusLost(evt);
            }
        });
        jTMarca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTMarcaActionPerformed(evt);
            }
        });
        jTMarca.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTMarcaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTMarcaKeyTyped(evt);
            }
        });

        jTColor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTColor.setForeground(new java.awt.Color(0, 80, 0));
        jTColor.setText("Ingrese el color");
        jTColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 80, 0), 2));
        jTColor.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jTColorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTColorFocusLost(evt);
            }
        });
        jTColor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTColorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTColorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNoRegistro)
                                        .addGap(11, 11, 11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTColor, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cBTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)))))
                        .addGap(26, 26, 26)))
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblNoRegistro)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(cBTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBSalirActionPerformed
    {//GEN-HEADEREND:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        imagen1 = (lblCredencialAnver.getIcon() != null);
        imagen2 = (lblCredencialRever.getIcon() != null);
        imagen3 = (lblTarjCirculacion.getIcon() != null);
        tamanio = (String) cBTamanio.getSelectedItem();
        System.out.println("Tamanio == " + tamanio);
        if (!jTNombre.getText().isEmpty()
                && (!jTPlacas.getText().isEmpty() && !jTPlacas.getText().equals("Ingrese el numero de placas"))
                && (!jTMarca.getText().isEmpty() && !jTMarca.getText().equals("Ingrese la marca"))
                && (!jTColor.getText().isEmpty() && !jTColor.getText().equals("Ingrese el color"))
                && (!jTNombre4.getText().isEmpty() && !jTNombre.getText().equals("Ingrese nombre completo aqui"))
                && (imagen1 == true && imagen2 == true && imagen3 == true)
                && (cBTamanio.getSelectedItem().equals("Pequeño")
                || cBTamanio.getSelectedItem().equals("Mediano")
                || cBTamanio.getSelectedItem().equals("Grande")))
        {
            //Proceso de guardar en la BD
            MetodosCRUD.guardaBD(jTNombre4.getText(), nombre, credencialAnver, credencialRever, tarjCirculacion, placas, color, marca, tamanio);
            //Proceso de limpiado de ventana
            lblCredencialAnver.setIcon(null);
            lblCredencialRever.setIcon(null);
            lblTarjCirculacion.setIcon(null);
            lblNoRegistro.setText(String.valueOf(MetodosCRUD.ultimoRegistro(1) + 1));
            lblTxtCredencialAnver.setText("No ha seleccionado ninguna imagen");
            lblTxtCredencialRever.setText("No ha seleccionado ninguna imagen");
            lblTxtTarjCirculacion.setText("No ha seleccionado ninguna imagen");
            jTNombre.setText("Ingrese nombre completo aqui");
            jTMarca.setText("Ingrese la marca");
            jTColor.setText("Ingrese el color");
            jTPlacas.setText("Ingrese el numero de placas");
            imagen1 = false;
            imagen2 = false;
            imagen3 = false;
            nombre = "";
            credencialAnver = "";
            credencialRever = "";
            tarjCirculacion = "";
            placas = "";
            color = "";
            marca = "";
            tamanio = "";
            cBTamanio.setSelectedIndex(0);
        } else
        {
            if (jTNombre.getText().isEmpty()
                    || !jTPlacas.getText().isEmpty()
                    || !jTMarca.getText().isEmpty()
                    || !jTColor.getText().isEmpty()
                    || !jTNombre4.getText().isEmpty()
                    || (imagen1 == true && imagen2 == true && imagen3 == true)
                    || (imagen1 == false && imagen2 == false && imagen3 == false)
                    && (cBTamanio.getSelectedItem().equals("Pequeño")
                    || cBTamanio.getSelectedItem().equals("Mediano")
                    || cBTamanio.getSelectedItem().equals("Grande")))
            {
                ErrorCampos codigo = new ErrorCampos(null, true);
                codigo.setModal(true);
                codigo.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTNombre4KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTNombre4KeyTyped
    {//GEN-HEADEREND:event_jTNombre4KeyTyped
        if (jTNombre4.getText().length() == 7)
        {
            evt.consume();
        } else
        {
            Character c = evt.getKeyChar();
            if (Character.isDigit(c))
            {
                evt.setKeyChar(c);
            } else
            {
                evt.setKeyChar('\b');
            }
        }
    }//GEN-LAST:event_jTNombre4KeyTyped

    private void jTNombre4FocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTNombre4FocusGained
    {//GEN-HEADEREND:event_jTNombre4FocusGained
        jTNombre4.setText(null);
    }//GEN-LAST:event_jTNombre4FocusGained

    private void jTNombre4FocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTNombre4FocusLost
    {//GEN-HEADEREND:event_jTNombre4FocusLost
        if (jTNombre4.getText().isEmpty())
        {
            jTNombre4.setText("Aquí se mostrará el código de barras");
        }
        
    }//GEN-LAST:event_jTNombre4FocusLost

    private void jTNombreFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTNombreFocusGained
    {//GEN-HEADEREND:event_jTNombreFocusGained
        if (!Caracteres.comparacion(jTNombre.getText(), "Ingrese nombre completo aqui"))
        {
            jTNombre.setText(null);
        }
    }//GEN-LAST:event_jTNombreFocusGained

    private void jTNombreFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTNombreFocusLost
    {//GEN-HEADEREND:event_jTNombreFocusLost
        nombre = jTNombre.getText();
        if (!Caracteres.comparacion(nombre, "Ingrese nombre completo aqui"))
        {
            jTNombre.setText("Ingrese nombre completo aqui");
        }
    }//GEN-LAST:event_jTNombreFocusLost

    private void jTNombreKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTNombreKeyReleased
    {//GEN-HEADEREND:event_jTNombreKeyReleased
        nombre = jTNombre.getText();
    }//GEN-LAST:event_jTNombreKeyReleased

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTNombreKeyTyped
    {//GEN-HEADEREND:event_jTNombreKeyTyped
        if (jTNombre.getText().length() == 30)
        {
            evt.consume();
        } else
        {
            Caracteres.va(evt);
        }
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTPlacasFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTPlacasFocusGained
    {//GEN-HEADEREND:event_jTPlacasFocusGained
        if (!Caracteres.comparacion(placas, "Ingrese el numero de placas"))
        {
            jTPlacas.setText(null);
        }
    }//GEN-LAST:event_jTPlacasFocusGained

    private void jTPlacasFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTPlacasFocusLost
    {//GEN-HEADEREND:event_jTPlacasFocusLost
        if (!Caracteres.comparacion(placas, "Ingrese el numero de placas"))
        {
            jTPlacas.setText("Ingrese el numero de placas");
        }
    }//GEN-LAST:event_jTPlacasFocusLost

    private void jTPlacasKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTPlacasKeyReleased
    {//GEN-HEADEREND:event_jTPlacasKeyReleased
        placas = jTPlacas.getText();
    }//GEN-LAST:event_jTPlacasKeyReleased

    private void jTPlacasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTPlacasKeyTyped
    {//GEN-HEADEREND:event_jTPlacasKeyTyped
        if (jTPlacas.getText().length() == 9)
        {
            evt.consume();
        } else
        {
            Character c = evt.getKeyChar();
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_jTPlacasKeyTyped

    private void jTMarcaFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTMarcaFocusGained
    {//GEN-HEADEREND:event_jTMarcaFocusGained
        if (!Caracteres.comparacion(marca, "Ingrese la marca"))
        {
            jTMarca.setText(null);
        }
    }//GEN-LAST:event_jTMarcaFocusGained

    private void jTMarcaFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTMarcaFocusLost
    {//GEN-HEADEREND:event_jTMarcaFocusLost
        if (!Caracteres.comparacion(marca, "Ingrese la marca"))
        {
            jTMarca.setText("Ingrese la marca");
        }
    }//GEN-LAST:event_jTMarcaFocusLost

    private void jTMarcaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTMarcaActionPerformed
    {//GEN-HEADEREND:event_jTMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMarcaActionPerformed

    private void jTMarcaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTMarcaKeyReleased
    {//GEN-HEADEREND:event_jTMarcaKeyReleased
        marca = jTMarca.getText();
    }//GEN-LAST:event_jTMarcaKeyReleased

    private void jTMarcaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTMarcaKeyTyped
    {//GEN-HEADEREND:event_jTMarcaKeyTyped
        if (jTMarca.getText().length() == 15)
        {
            evt.consume();
        } else
        {
            Caracteres.va(evt);
        }
    }//GEN-LAST:event_jTMarcaKeyTyped

    private void jTColorFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTColorFocusGained
    {//GEN-HEADEREND:event_jTColorFocusGained
        if (!Caracteres.comparacion(color, "Ingrese el color"))
        {
            jTColor.setText(null);
        }
    }//GEN-LAST:event_jTColorFocusGained

    private void jTColorFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTColorFocusLost
    {//GEN-HEADEREND:event_jTColorFocusLost
        if (!Caracteres.comparacion(color, "Ingrese el color"))
        {
            jTColor.setText("Ingrese el color");
        }
    }//GEN-LAST:event_jTColorFocusLost

    private void jTColorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTColorKeyReleased
    {//GEN-HEADEREND:event_jTColorKeyReleased
        color = jTColor.getText();
    }//GEN-LAST:event_jTColorKeyReleased

    private void jTColorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTColorKeyTyped
    {//GEN-HEADEREND:event_jTColorKeyTyped
        if (jTColor.getText().length() == 15)
        {
            evt.consume();
        } else
        {
            Caracteres.va(evt);
        }
    }//GEN-LAST:event_jTColorKeyTyped

    private void btnCredencialAnverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCredencialAnverActionPerformed
    {//GEN-HEADEREND:event_btnCredencialAnverActionPerformed
        JFileChooser credAnver = new JFileChooser();
        int opc = credAnver.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION)
        {
            String ruta = credAnver.getSelectedFile().getPath();
            rsscalelabel.RSScaleLabel.setScaleLabel(lblCredencialAnver, ruta);
            lblCredencialAnver.setText("");
            lblTxtCredencialAnver.setText(credAnver.getSelectedFile().getName());
            credencialAnver = ruta;
        } else
        {
            System.out.println("No se selecciono ningun archivo.");
        }
    }//GEN-LAST:event_btnCredencialAnverActionPerformed

    private void btnTarjCirculacionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnTarjCirculacionActionPerformed
    {//GEN-HEADEREND:event_btnTarjCirculacionActionPerformed
        JFileChooser tarjCirc = new JFileChooser();
        int opc = tarjCirc.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION)
        {
            String ruta = tarjCirc.getSelectedFile().getPath();
            rsscalelabel.RSScaleLabel.setScaleLabel(lblTarjCirculacion, ruta);
            lblCredencialRever.setText("");
            lblTxtTarjCirculacion.setText(tarjCirc.getSelectedFile().getName());
            tarjCirculacion = ruta;
        } else
        {
            System.out.println("No se selecciono ningun archivo.");
        }
    }//GEN-LAST:event_btnTarjCirculacionActionPerformed

    private void btnCredencialReverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCredencialReverActionPerformed
    {//GEN-HEADEREND:event_btnCredencialReverActionPerformed
        JFileChooser credRever = new JFileChooser();
        int opc = credRever.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION)
        {
            String ruta = credRever.getSelectedFile().getPath();
            rsscalelabel.RSScaleLabel.setScaleLabel(lblCredencialRever, ruta);
            lblTarjCirculacion.setText("");
            lblTxtCredencialRever.setText(credRever.getSelectedFile().getName());
            credencialRever = ruta;
        } else
        {
            System.out.println("No se selecciono ningun archivo.");
        }
    }//GEN-LAST:event_btnCredencialReverActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        barcode.setCodeType(new Interleaved25());
        //barcode.setCodeType(new Code39());

        // nuestro valor a codificar y algunas configuraciones mas
        barcode.setCode(jTNombre4.getText());
        barcode.setCheckDigit(true);

        imagen = barcode.draw(new BufferedImage(168 , 104, BufferedImage.TYPE_INT_RGB));

        ImageIcon barras = new ImageIcon(imagen);
        this.lblCode.setIcon(barras);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroVhIncorp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroVhIncorp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroVhIncorp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroVhIncorp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegistroVhIncorp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCredencialAnver;
    private javax.swing.JButton btnCredencialRever;
    private javax.swing.JButton btnTarjCirculacion;
    private javax.swing.JComboBox<String> cBTamanio;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTColor;
    private javax.swing.JTextField jTMarca;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTNombre4;
    private javax.swing.JTextField jTPlacas;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblCredencialAnver;
    private javax.swing.JLabel lblCredencialRever;
    private javax.swing.JLabel lblNoRegistro;
    private javax.swing.JLabel lblTarjCirculacion;
    private javax.swing.JLabel lblTxtCredencialAnver;
    private javax.swing.JLabel lblTxtCredencialRever;
    private javax.swing.JLabel lblTxtTarjCirculacion;
    // End of variables declaration//GEN-END:variables
}
